[package]
name = "rust_utils"
version = "0.1.0"
authors = ["Daniel Sonne Lehnberg <doddy@doddy.se>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
uuid = {version = "0.8.1", features = ["v4"]}